export default function DisclaimerPage() {
  return (
    <main
      style={{
        maxWidth: "900px",
        margin: "40px auto",
        padding: "20px",
        lineHeight: "1.7",
        fontSize: "16px"
      }}
    >

      <h1 style={{marginBottom:"20px"}}>Disclaimer</h1>

      <p>
        The calculators and information provided on RateCalcNow are intended
        for general informational and educational purposes only.
      </p>

      <p>
        While we strive to ensure that calculations are accurate, we make no
        guarantees regarding the completeness, reliability, or accuracy of
        the results generated by these tools.
      </p>

      <h2 style={{marginTop:"30px"}}>No Financial Advice</h2>

      <p>
        The content and calculators on this website do not constitute financial,
        legal, tax, or investment advice. Users should consult with qualified
        professionals before making financial decisions.
      </p>

      <h2 style={{marginTop:"30px"}}>Use at Your Own Risk</h2>

      <p>
        By using this website, you acknowledge that any reliance on the
        calculators or information provided is at your own risk.
      </p>

    </main>
  )
}